"use strict";

import DeltaObserver from "./delta";

/*
 * observer that latches results into a text buffer suitable for sending
 * to influxdb. you provide a function which will attempt to POST the
 * resulting document to your influxdb server(s).
 *
 * - registry: (optional) used to fetch the crow version for reporting
 * - observer: `String => void` gets the document to POST, as snapshots are
 *     emitted
 */
export function influxObserver(registry, observer) {
  const header = "# generated by crow " + (registry ? registry.version : "");

  /*
   * generate the text body of a POST to influxdb to tell it about all our
   * juicy metrics.
   */
  function generate(snapshot) {
    const lines = [ header ];

    const map = snapshot.flatten((name, tags, subkey) => {
      if (subkey) tags = tags.merge({ p: subkey });
      const taglist = tags.format((k, v) => k + "=" + v, list => list.join(","));
      return name + (taglist.length > 0 ? "," + taglist : "");
    });

    for (const [ name, { value } ] of map) {
      // add zeros to timestamp to make it nanoseconds instead of milliseconds.
      lines.push(`${name} value=${value} ${snapshot.timestamp}000000`);
    }

    observer(lines.join("\n") + "\n");
  }

  const d = new DeltaObserver();
  d.addObserver(generate);
  return d.observer;
}

/*
 * Given a 'request' (or request-like) module, create an observer attached
 * to a registry that will `POST` snapshots in influxdb format.
 *
 *     import { exportInflux, MetricsRegistry } from "crow-metrics";
 *     import request from "request";
 *
 *     const registry = new MetricsRegistry();
 *     exportInflux(registry, request, "influxdb.prod.example.com", "prod");
 *
 * Options:
 *   - hostname: influxdb host (default: "influxdb.local:8086")
 *   - database: influxdb database name (default: "test")
 *   - url: use a custom url, instead of `http://(hostname)/write?db=(database)`
 *   - timeout: how long to wait before giving up (msec, default 5000)
 *   - log: bunyan-style log for reporting errors
 */
export function exportInflux(registry, request, options = {}) {
  const hostname = options.hostname || "influxdb.local:8086";
  const database = options.database || "test";
  const timeout = options.timeout || 5000;

  registry.addObserver(influxObserver(registry, body => {
    const requestOptions = {
      method: "post",
      url: options.url || `http://${hostname}/write?db=${database}`,
      headers: { "content-type": "text/plain" },
      timeout,
      body
    };

    request(requestOptions, error => {
      if (error && options.log) options.log.error({ err: error }, "Unable to write metrics to influxdb");
    });
  }));
}
